### ISSUE TITLE
Fullscreen totally breaks now

### ISSUE THREAD

**Issue by TylerFisher** [nprapps/rockymountain#103]
The aframe update does weird things with the canvas size.

**Comment by lindamood** [comment]
This may already be on your radar, but...

I'm noticing strange aframe sizing issues in the guided experience as well. The canvas is being stretched and the image is distorting. 

In click and drag mode the size of the canvas does not update, if the browser size changes.

**Comment by TylerFisher** [comment]
Got all these things in 2b929caebf333a68ab35f21667f0709ad1d885e1
