### ISSUE TITLE
title card css animation pano

### ISSUE THREAD

**Issue by lindamood** [nprapps/rockymountain#114]
https://www.flickr.com/gp/constantcurve/00y6nd

**Comment by TylerFisher** [comment]
Feeling good about this, on a branch: https://github.com/nprapps/rockymountain/tree/pano-titlecard

**Comment by lindamood** [comment]
Yeah, that's really cool. I think this will be effective.

Two things:
1. can we get rid of the horizontal scrollbars?
2. Can the width/height of the pano always fill the entirety of browser window? I resized my browser during the animation and when the pano ended there was a strip of black on the edge of the screen (see attached) 

![a_virtual_reality_reflection_on_deep_time_and_index_html_ __users_lindamood_code_rockymountain_and_slack](https://cloud.githubusercontent.com/assets/1319852/16452291/a8d9396c-3dd5-11e6-8d13-09e568de1e85.png)

**Comment by lindamood** [comment]
The animation does not work in OS X Safari right now.

**Comment by TylerFisher** [comment]
merged in, it pretty much works now
