### ISSUE TITLE
Write IE notice on title screen

### ISSUE THREAD

**Issue by lindamood** [nprapps/rockymountain#116]

**Comment by lindamood** [comment]
The title screen doesn't show up in IE11/Win7.

**Comment by lindamood** [comment]
The good news is the experience is working in Edge/Win10 on my virtual machine.

**Comment by TylerFisher** [comment]
hm, works in my virtual environment, same specs 
![screen shot 2016-07-05 at 2 04 01 pm](https://cloud.githubusercontent.com/assets/1077075/16594660/66ad61b0-42b9-11e6-9aa7-d486e79d806e.png)

**Comment by lindamood** [comment]
OK, I'll see if I can get this running in my VM. Not sure what to make of the Win7/IE11 laptop at this point.
