### ISSUE TITLE
Icon on MOZ modal to enter experience on desktop

### ISSUE THREAD

**Issue by brmayes** [nprapps/rockymountain#142]

**Comment by lindamood** [comment]
can you provide a description for this ticket? Is the icon not showing up?

**Comment by brmayes** [comment]
It's showing up but on desktop it shows a phone icon vs the icon we have previously used for click and drag. I'm assuming it does so because we are using the exact same thing for the mobile version. It's a very small thing, so I'm not sure if we want to switch it out or just let it be. Just wanted to create an issue so I remembered to bring it up.

**Comment by lindamood** [comment]
good catch!

**Comment by lindamood** [comment]
Please swap this with the desktop icon that appears on the interstitial.
