### ISSUE TITLE
place all VR scene annotations near the subject of the scene.

### ISSUE THREAD

**Issue by lindamood** [nprapps/rockymountain#154]

**Comment by brmayes** [comment]
I've gone through and looked at the current locations of the annotations. It seems like only two of them absolutely need to be moved, and two other ones should just be lowered. @TylerFisher, when you figure out how to do custom annotation locations, will you let me know so I can adjust them?

Here's the list:
- move mountain-building left
- hollowell park needs to be moved 180°
- move longs-peak down
- gem-lake could be moved down
