### ISSUE TITLE
test new FB asset types 

### ISSUE THREAD

**Issue by lindamood** [nprapps/rockymountain#168]
check with the engagement team regarding what types of assets we might want to test.

**Comment by TylerFisher** [comment]
360º image: 
![screen shot 2016-07-13 at 11 50 22 am](https://cloud.githubusercontent.com/assets/1077075/16809958/20f3ba10-48f0-11e6-9eee-5c2f49bda0b8.png)

You just upload the image, nothing special to do. Facebook recognizes it as equirectangular and sets everything up. Works just like a normal photo post.

**Comment by TylerFisher** [comment]
The only new thing we're gonna try is 360º images
