### ISSUE TITLE
Change starting position for MOZ

### ISSUE THREAD

**Issue by brmayes** [nprapps/rockymountain#180]

**Comment by brmayes** [comment]
- mountain-building so you don't land directly on the backpack
- hollowell-park 
- moraine park
- fern lake
- glacier gorge

**Comment by TylerFisher** [comment]
At the moment, the starting position of a moment of zen is the last position of your camera. I'll try to force it to reset on entrance.

**Comment by TylerFisher** [comment]
Banging my head against the wall here. Aframe really doesn't like you updating the camera position.

**Comment by brmayes** [comment]
Any update on this? If not, I'm sure it will be fine. This seems pretty low priority.

**Comment by TylerFisher** [comment]
I don't think there's anything I can do about it. I can't even find in aframe where to patch or change things.

**Comment by brmayes** [comment]
Gotcha. Will close then.
