### ISSUE TITLE
Weird jump in loading MOZ cards glitch?

### ISSUE THREAD

**Issue by brmayes** [nprapps/rockymountain#185]
I have a video (too large to upload) but it looks like the previous screen is popping up before changing to the link that was clicked on. Might only happen on a device with really fast connection that hasn't been cached.

**Comment by TylerFisher** [comment]
Hmmm... two questions:
1. Can you make it happen reliably?
2. Are you testing locally or on stage?

**Comment by TylerFisher** [comment]
Yeah, really can't replicate this.

**Comment by brmayes** [comment]
Whoops, sorry. Didn't see this comment. It's on stage. I don't think it's a huge deal, but I can walk over and show you what's happening. It's happened in multiple instances.

**Comment by brmayes** [comment]
I'm also not 100% sure it's actually fixable.

**Comment by TylerFisher** [comment]
If you can make it happen I'd like to see it
