### ISSUE TITLE
Maybe let's remove fullscreen

### ISSUE THREAD

**Issue by TylerFisher** [nprapps/rockymountain#186]
It doesn't really work anywhere reliably and I haven't been able to patch aframe correctly to handle it.

**Comment by TylerFisher** [comment]
I put this on a branch, in case we decide to do it.

**Comment by brmayes** [comment]
This might be the way to go. I really like the full screen mode. I think it's the best for the immersice feeling that we're going for, but if it's causing this many problems (with 4/5 browsers), then maybe we kill it?

**Comment by TylerFisher** [comment]
Hey, rolling back aframe fixed this!
