### ISSUE TITLE
Tablet shows VR mode

### ISSUE THREAD

**Issue by brmayes** [nprapps/rockymountain#188]

**Comment by TylerFisher** [comment]
Wes and I have talked about this. This is low-priority, and we're okay with leaving it on if we don't get to it.

**Comment by brmayes** [comment]
It takes me to 360° mode when I click on that button. Is that what's supposed to happen?

**Comment by TylerFisher** [comment]
ha, nope!

**Comment by TylerFisher** [comment]
This is probably fixed now -- that was a more widespread issue.

**Comment by brmayes** [comment]
Yep. It is.
