### ISSUE TITLE
Entering/exiting VR in Android is very different from iOS

### ISSUE THREAD

**Issue by TylerFisher** [nprapps/rockymountain#200]
When you enter VR in Android, it forces into fullscreen mode and automatically rotates the device into landscape. The modal flashes for a second and goes away. Not ideal, but also default aframe behavior.

The only way to exit VR on Android is to use the native back button. It's actually pretty nice, but our instructions do not match this. You cannot rotate your device to exit. Which means we might have to serve a different image at the end that tells you to use the back button. The back button does work exactly like rotating your device does on iOS.

**Comment by lindamood** [comment]
I'll work on a new image to drop in at the end of the story.
