### ISSUE TITLE
Scrolling problem on interstitial card

### ISSUE THREAD

**Issue by brmayes** [nprapps/rockymountain#202]
Specifically on iPhone SE (haven't noticed it anywhere else yet), it won't let you scroll and it only shows to the top of the VR section. If you click on 360 mode -> replay the story -> interstitial card it will let you scroll. Not sure why this makes a difference.

**Comment by lindamood** [comment]
I'll investigate this as time permits.

**Comment by TylerFisher** [comment]
My fix broke everything. Gotta find a better solution.
