### ISSUE TITLE
Device Testing

### ISSUE THREAD

**Issue by lindamood** [nprapps/rockymountain#21]
- [x] Device testing: iPhone Safari 360° mode
- [x] Device testing: iPhone Safari VR mode 
- [x] Device testing: iPhone Chrome/Webkit 360° mode
- [x] Device testing: iPhone Chrome/Webkit VR mode  
- [x] Device testing: Android phone 360° mode
- [x] Device testing: Android phone VR mode
- [x] Device testing: Android tablet
- [x] Device testing: iPad

Title card
- Does the animation load smoothly?
- Does the begin button work?
- Any display issues?

Interstitial card
- Does the loading animation work on a slow connection?
- Are the correct buttons showing up?
- Do all the buttons and links work as expected?
- Is the sponsorship showing up correctly?
- Do all the sponsorship links work?
- Any display issues?

Scene card
- Does the story play through in guided experience mode without error?
- Does the story play through in click and drag mode without error?
- Is the audio playing?
- Can the audio be paused?
- Can the progress bar be selected to seek the audio?
- Does the WebVR button work correctly?
- When you enter WebVR mode when the phone is held vertically, do you see the "rotate your phone notice?"
- When you enter WebVR mode when the phone is held horizontally, do you enter VR mode immediately?
- At the end of the VR story, is there a notice that tells you to rotate your device to exit?
- When you rotate your device to exit VR mode at the end of the story, do you see the conclusion card?
- Are all the annotations correct in VR mode?
- Are all the annotations correct in 360° mode?
- Does the more 360° scenes button take you to the conclusion card?
- Any display issues?

Conclusion card
- If you arrived at the conclusion card via the story, do you see the replay the story button?
- Does the replay the story button take you to the interstitial card?
- If you arrived at the conclusion card via a MOZ, do you see the story promo?
- Does the "view 360° story" button take you to the interstitial card?
- Do the thumbnail images link to the correct MOZ?
- Is the sponsorship showing up correctly?
- Do all the sponsorship links work?

Moment of Zen (MOZ)
- If you arrived at a MOZ via a permalink, does the intro modal show up correctly?
- Does the enter 360° mode button work correctly?
- Does the WebVR button work correctly?
- When you enter WebVR mode when the phone is held vertically, do you see the "rotate your phone notice?"
- When you enter WebVR mode when the phone is held horizontally, do you enter VR mode immediately?
- Is audio playing?
- Does the mute button mute the audio?
- Are all the annotations correct in VR mode?
- Are all the annotations correct in 360° mode?
- Does the "learn more about this location" link open the detail modal?
- Does the close detail modal button work correctly?
- Does clicking on the "virtual reality reflection on deep time" link take you to the interstial card?
- Is the rotation of the 360° image correct? When you enter the experience, are you looking at the subject or the image or a random part of the image?

**Comment by brmayes** [comment]
I've finished all the device testing on my end, and @TylerFisher is going to finish up the testing on the Android side. Everything looks good, except for the tickets I've already made. iPhone Chrome is a little more glitchy than safari, but nothing that seems to repeat enough to be a large concern.

Once the Android testing is complete, this can be closed for now.

**Comment by TylerFisher** [comment]
Tested. Android is weird. Tickets coming.
