### ISSUE TITLE
Create 3 panning gifs for use as twitter images.

### ISSUE THREAD

**Issue by lindamood** [nprapps/rockymountain#211]
Use:
- Dream Lake (scene 1)
- Emerald Lake (scene 2)
- Steep Mountain/Hollowell high (scene 7)

**Comment by lindamood** [comment]
A GIF may fail during Tweet creation even if it is within the filesize limit. Adhere to the following constraints to improve success rates.

Resolution should be <= 1280x1080 (width x height)
Number of frames <= 350
Number of pixels (width \* height \* num_frames) <= 300 million

https://dev.twitter.com/rest/media/uploading-media

**Comment by lindamood** [comment]
Here's an example of logo placement. You don't need to worry about the credit for these gifs.

![cnp8qwmwaaaxnek](https://cloud.githubusercontent.com/assets/1319852/16956132/2fe30878-4da5-11e6-8133-9d780d466ce1.jpg)

**Comment by lindamood** [comment]
This logo should work. 
![npr-white](https://cloud.githubusercontent.com/assets/1319852/16956148/42c2efee-4da5-11e6-9e10-a9b35f37e87b.png)

**Comment by brmayes** [comment]
Will do. Not happy with how the screen recording quality has been turning out. I will probably animate them myself in AE for sake of time and frustration.
