### ISSUE TITLE
Seamus Stuff

### ISSUE THREAD

**Issue by lindamood** [nprapps/rockymountain#25]
- [x] Create Seamus shell page
- [x] Request shell page redirect

https://github.com/nprapps/workinprivate/blob/master/shell_pages.md

**Comment by lindamood** [comment]
The story URL is documented in our social strategy google doc.

**Comment by lindamood** [comment]
Oh, and please add the Seamus ID to the social strategy planning doc.

**Comment by TylerFisher** [comment]
Once we're settled on a final headline I can finalize the stub page and request redirects (the redirect path changes every time the URL changes)

**Comment by lindamood** [comment]
OK, the final headline is in the spreadsheet: Stand At The Edge Of Earth And Time

**Comment by TylerFisher** [comment]
Shell page is scheduled to publish, redirects requested. Will close this once we have promotional images I can associate with the shell page.

**Comment by TylerFisher** [comment]
I added the Longs Peak image as default for the shell page. I _think_ I got this all right.

**Comment by lindamood** [comment]
Yeah, Longs is the right image.

**Comment by TylerFisher** [comment]
For posterity, Seamus ID is 486603667
