### ISSUE TITLE
Add David to this github project. 

### ISSUE THREAD

**Issue by lindamood** [nprapps/rockymountain#4]

**Comment by TylerFisher** [comment]
Invite sent.

**Comment by eads** [comment]
👋

**Comment by eads** [comment]
Actually, are we talking about a different David?

**Comment by TylerFisher** [comment]
Yeah, David Al-Ibrahim, our resident 360 photo expert.

**Comment by eads** [comment]
Too bad there's no "It wasn't me" bitmoji.
