### ISSUE TITLE
Will this story work in IE11?

### ISSUE THREAD

**Issue by lindamood** [nprapps/rockymountain#42]
Do some research to see if webvr-boilerplate supports IE11

**Comment by lindamood** [comment]
@TylerFisher https://github.com/aframevr/aframe/issues/1475

**Comment by TylerFisher** [comment]
Cool. I can try the polyfill and see if it's passable.

**Comment by lindamood** [comment]
Cool.

it works great in Chrome and FF on a PC, BTW.  

And our target platform is mobile, so IE11 support is not a high priority.

**Comment by lindamood** [comment]
Just tested on a PC and sadly the polyfill doesn't work in IE11.

**Comment by lindamood** [comment]
See: https://github.com/nprapps/rockymountain/issues/64
