### ISSUE TITLE
Reset position on each scene change

### ISSUE THREAD

**Issue by lindamood** [nprapps/rockymountain#7]
If a user clicks and drags a prior scene, that overrides the image rotation settings for all following scenes.

**Comment by TylerFisher** [comment]
This is more complicated than it sounds. By ceding control to the user, a-frame's controls automatically override anything set in JavaScript. From a VR standpoint, I totally understand why this is the case, just frustrating. There are some other things I can try though.

**Comment by lindamood** [comment]
If we can't get this to work, we should consider removing click & drag from the desktop experience.

**Comment by TylerFisher** [comment]
This is happening on the guided experience. Again, not possible in click and drag.
