### ISSUE TITLE
figure out how to add text to a vr scene

### ISSUE THREAD

**Issue by lindamood** [nprapps/rockymountain#89]

**Comment by TylerFisher** [comment]
I looked into:
- https://github.com/ngokevin/aframe-text-component
- https://github.com/scenevr/htmltexture-component

But I can't seem to natively render text onto the scene. I think our best bet is going to be transparent pngs for now.

**Comment by lindamood** [comment]
Trying with a PNG.

**Comment by TylerFisher** [comment]
dupe, gonna do this with png annotations.
